default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "student") %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: pos_mockup_backend_development

test:
  <<: *default
  database: pos_mockup_backend_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>